<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>

<h3 style="color:purple">Sample problem of predicting salaries for future candidates</h3>

### This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates.

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('hiring.csv')

In [3]:
df.shape

(8, 4)

In [4]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [5]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
from word2number import w2n

In [10]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [11]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [12]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [13]:
#seperating X and y
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [14]:
#dividing into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [22]:
#creating linear regression model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [23]:
#fitting the training data
regressor.fit(X_train,y_train)

LinearRegression()

In [28]:
regressor.coef_

array([3125.76177285, 2602.21606648, 2232.13296399])

In [29]:
regressor.intercept_

10486.9806094183

In [24]:
#prediction
y_pred = regressor.predict(X_test)

In [25]:
#checking the r2score
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9455047731446475

#### 2 yr experience, 9 test score, 6 interview score

In [26]:
regressor.predict([[2,9,6]])

array([53551.2465374])

#### 12 yr experience, 10 test score, 10 interview score

In [27]:
regressor.predict([[12,10,10]])

array([96339.61218837])